# Generated by Django 2.2.4 on 2019-10-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='account',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='account',
            name='birthdate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='birthplace',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='middlename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='prefix',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='suffix',
            field=models.CharField(default='', max_length=100),
        ),
    ]
