# Generated by Django 2.2.4 on 2019-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMain', '0002_auto_20191022_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='deleted',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='timestamp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
