# Generated by Django 2.2.4 on 2019-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMain', '0002_auto_20191013_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics'),
        ),
    ]
